title: Jiandanjinxin AI Conference Deadlines
description: Countdowns to top CV/ML/SP/DM/MIC/SI/AC/AI conference deadlines
author: jiandanjinxin

domain: "https://github.com/jiandanjinxin"
baseurl: ""

twitter_hashtag: machinelearning
github_username: jiandanjinxin
github_repo: jiandanjinxin.github.io

markdown: kramdown
ga_id:

include: ['_pages']
